console.log('******************************************************************');
console.log('*                           Notice                               *');
console.log('******************************************************************');
console.log('*  If you are using Node v0.12 or v0.10, you should install      *');
console.log('*  Newman v1.x:                                                  *');
console.log('*                                                                *');
console.log('*                   npm install newman@1                         *');
console.log('*                                                                *');
console.log('*  Deprecation: Newman v3 onwards will deprecate the use of DOM  *');
console.log('*  related libraries, such as JQuery and Backbone. For details,  *');
console.log('*  check https://www.getpostman.com/docs/sandbox                 *');
console.log('******************************************************************');
