name: CI

on:
    push:
        paths-ignore:
            - "*.md"
    pull_request:
        branches: [$default-branch]
    schedule:
        - cron: "0 12 * * 0"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        name: Tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                node-version: [16, 18]
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Run tests
              run: npm run test

    coverage:
        name: Coverage
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js 20
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: "npm"

            - name: Install
              run: npm ci

            - name: Run unit tests
              run: |
                  npm run test-unit
                  bash <(curl -s https://codecov.io/bash) -c -Z -f .coverage/coverage-final.json -F unit -t ${{ secrets.CODECOV_TOKEN }}

            - name: Run integration tests
              run: |
                  npm run test-integration
                  bash <(curl -s https://codecov.io/bash) -c -Z -f .coverage/coverage-final.json -F integration -t ${{ secrets.CODECOV_TOKEN }}

            - name: Run CLI tests
              run: |
                  npm run test-cli
                  bash <(curl -s https://codecov.io/bash) -c -Z -f .coverage/coverage-final.json -F cli -t ${{ secrets.CODECOV_TOKEN }}

            - name: Run library tests
              run: |
                  npm run test-library
                  bash <(curl -s https://codecov.io/bash) -c -Z -f .coverage/coverage-final.json -F library -t ${{ secrets.CODECOV_TOKEN }}
